Eventique/Models/Photographer.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Moq;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
namespace Eventique.Models
{
    public class Photographer
    {

        [Key]
        public int Ph_Id { get; set; }
        public string Ph_Name  { get; set; }
        public float Rate { get; set; }
        public List<Album> ListAlbum { get; set; }
        public float Ph_Price { get; set; }
        public string Ph_Offers { get; set; }
        public string Ph_Address { get; set; }
        public string Ph_PhoneNumber { get; set; }
        public List<AvailableDate> Ph_AvailableDate { get; set; }
        public string Ph_CameraType { get; set; }
        public List<Review> Ph_Reviews { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        [NotMappedAttribute]
        public List<IFormFile> ImageFilePath{ get; set; }
        public List<PhotographerRequest> Ph_Requests { get; set; }
        public IdentityUser Users { get; set; }
        public string TestDate { get; set; }
        public List<PriceOffer> OffersList { get; set; }
        public Photographer()
        {
            ImagePath = "/Images/pho_avatar.jpg";
            ListAlbum = new List<Album>();
            Ph_AvailableDate = new List<AvailableDate>();
            Ph_Reviews = new List<Review>();
            Ph_Requests = new List<PhotographerRequest>();
            OffersList = new List<PriceOffer>();
        }
    }
}

Eventique/Controllers/PhotographersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Eventique.Data;
using Eventique.Models;
using Eventique.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Eventique.Controllers
{
    [Authorize(Roles = "Photographer")]
    public class PhotographersController : Controller
    {
        private readonly ApplicationDbContext context;
        private IHostingEnvironment Environment;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ILogger<PhotographersController> _logger;


        public PhotographersController(ApplicationDbContext _context , IHostingEnvironment _environment,
             UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager,
            ILogger<PhotographersController> logger)
        {
            context = _context;
            Environment = _environment;
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;

        }
        public IActionResult Index()
        {
            Photographer p = new Photographer();
            return View();
        }

        //public IActionResult PhoEdit(int id)
        //{
        //    Photographer p = new Photographer();
        //    p = context.Photographers.Where(p => p.Ph_Id == id).FirstOrDefault();
        //    context.Albums.ToList();
        //    context.Images.ToList();
        //    context.Users.ToList();
        //    return View(p);
        //}

        public IActionResult TestPhoEdit(int id)
        {
            Photographer p = new Photographer();
            p = context.Photographers.Where(p => p.Ph_Id == id).FirstOrDefault();
            context.Albums.ToList();
            context.Reviews.ToList();
            context.Members.ToList();
            context.Images.ToList();
            context.Users.ToList();
            context.PriceOffers.ToList();
            context.PhotographerRequests.ToList();
            context.Members.ToList();

            return View(p);
        }
        //public IActionResult CreateAlbum()
        //{
        //    Photographer p = new Photographer();
        //    //p = context.Photographers.Where(p => p.Ph_Id == id).FirstOrDefault();
        //    context.Albums.ToList();
        //    context.Images.ToList();
        //    return View();
        //}
        public IActionResult CreateNewAlbum()
        {
            Photographer p = new Photographer();
            //p = context.Photographers.Where(p => p.Ph_Id == id).FirstOrDefault();
            context.Albums.ToList();
            context.Images.ToList();
            return View();
        }

   
        [HttpPost]
        public IActionResult CreateNewAlbum(int id, Album b)
        {
            string wwwPath = this.Environment.WebRootPath;
            string contentPath = this.Environment.ContentRootPath;

            string path = Path.Combine(this.Environment.WebRootPath, "Images");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            List<Image> imgP = new List<Image>();
            List<string> uploadedFiles = new List<string>();
            foreach (IFormFile postedFile in b.ImageFilePath)
            {
                string fileName = Path.GetFileName(postedFile.FileName);
                using (FileStream stream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                {
                    postedFile.CopyTo(stream);
                    uploadedFiles.Add(fileName);
                    imgP.Add(new Image() { Img_Path = "/Images/" + fileName });
                }

            }
           
            b.MyProperty = imgP;
            Photographer po = new Photographer();
            po = context.Photographers.Where(s => s.Ph_Id == id).FirstOrDefault();
            context.Albums.ToList();
            context.Images.ToList();
            context.Albums.Add(b);
            po.ListAlbum.Add(b);
            context.SaveChanges();
            return RedirectToAction("TestPhoEdit", new { id = id });
        }



        public IActionResult EditPho(int id)
        {
            Photographer p = new Photographer();
            p = context.Photographers.Where(p => p.Ph_Id == id).FirstOrDefault();
            context.Albums.ToList();
            context.Images.ToList();
            context.Users.ToList();
            return View(p);
        }

        [HttpPost]
        public IActionResult EditPho(Photographer p)
        {
            if (ModelState != null)
            {
                string wwwPath = this.Environment.WebRootPath;
                string contentPath = this.Environment.ContentRootPath;

                string path = Path.Combine(this.Environment.WebRootPath, "Images");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                List<string> uploadedFiles = new List<string>();
                if (p.ImageFilePath != null)
                {
                    foreach (IFormFile postedFile in p.ImageFilePath)
                    {
                        string fileName = Path.GetFileName(postedFile.FileName);
                        using (FileStream stream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                        {
                            postedFile.CopyTo(stream);
                            uploadedFiles.Add(fileName);
                            string imgP = "/Images/" + fileName;
                            Photographer edited = new Photographer();
                            edited = context.Photographers.Where(po => po.Ph_Id == p.Ph_Id).FirstOrDefault();
                            edited.Ph_Name = p.Ph_Name;
                            edited.Ph_PhoneNumber = p.Ph_PhoneNumber;
                            edited.Ph_Price = p.Ph_Price;
                            edited.Ph_Address = p.Ph_Address;
                            edited.Ph_CameraType = p.Ph_CameraType;
                            edited.Ph_Offers = p.Ph_Offers;
                            edited.Description = p.Description;
                            edited.ImagePath = imgP;
                            edited.TestDate = p.TestDate;
                            context.SaveChanges();
                            return RedirectToAction("TestPhoEdit", new { id = p.Ph_Id });
                        }
                    }
                }
                else
                {
                    Photographer edited = new Photographer();
                    edited = context.Photographers.Where(po => po.Ph_Id == p.Ph_Id).FirstOrDefault();
                    edited.Ph_Name = p.Ph_Name;
                    edited.Ph_PhoneNumber = p.Ph_PhoneNumber;
                    edited.Ph_Price = p.Ph_Price;
                    edited.Ph_Address = p.Ph_Address;
                    edited.Ph_CameraType = p.Ph_CameraType;
                    edited.Ph_Offers = p.Ph_Offers;
                    edited.Description = p.Description;
                    edited.ImagePath = p.ImagePath;
                    edited.TestDate = p.TestDate;
                    context.SaveChanges();
                    return RedirectToAction("TestPhoEdit", new { id = p.Ph_Id });

                }
            }
            return View(p);
        }

        //For displaying deals in photographer page
        public IActionResult Deals()
        {
            var user = User.FindFirst(ClaimTypes.NameIdentifier);
            Photographer ph = context.Photographers.Where(h => h.Users.Id == user.Value).FirstOrDefault();
            //p = context.Photographers.Where(p => p.Ph_Id == id).FirstOrDefault();
            context.Images.ToList();
            context.Users.ToList();
            context.PhotographerRequests.ToList();
            context.Members.ToList();
            return View(ph);
        }

        [HttpPost]
        public IActionResult AcceptDeal (int id)
        {
            var user = User.FindFirst(ClaimTypes.NameIdentifier);
            Photographer ph = context.Photographers.Where(h => h.Users.Id == user.Value).FirstOrDefault();
            PhotographerRequest pr = context.PhotographerRequests.Where(fr => fr.ID == id).FirstOrDefault();
            pr.Status = "Accepted";
            var DateLi = ph.TestDate.Split(",");
            List<string> dt = new List<string>();
            dt = DateLi.ToList();
            foreach (var item in dt)
            {
                if (pr.Date == item)
                {
                    dt.Remove(item);
                    break;
                }

            }
            StringBuilder st = new StringBuilder();
            for (int i = 0; i < dt.Count; i++)
            {
                if (i == dt.Count-1 )
                {
                    st.Append(dt[i]);
                }
                else
                {
                    st.Append(dt[i] + ",");
                }
            }
            ph.TestDate = st.ToString();
            context.SaveChanges();

            //GMailer.GmailUsername = "fady.ragaa48@gmail.com";
            //GMailer.GmailPassword = "fady2020";

            //GMailer mailer = new GMailer();
            //mailer.ToEmail = "bahersaweres@gmail.com";
            //mailer.Subject = "Eventique Website";
            //mailer.Body = "Thanks for Registering your Booking .<br> your booking accepted now</a>";
            //mailer.IsHtml = false;
            //mailer.Send();
            return RedirectToAction("Deals");
        }

        [HttpPost]
        public IActionResult CancelDeal(int id)
        {

Eventique/Views/Photographers/ChangePassword.cshtml
@model Eventique.ViewModel.ChangePassVM
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width" />
    <title>ChangePassword</title>
</head>
<body>
    <h2 style="margin-left:500px">Change Password</h2>
    <div class="row justify-content-center mb-5 pb-2">
        <div class="col-md-4">
            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="CurrentPassword"></label>
                    <input asp-for="CurrentPassword" class="form-control" />
                    <span asp-validation-for="CurrentPassword" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NewPassword"></label>
                    <input asp-for="NewPassword" class="form-control" />
                    <span asp-validation-for="NewPassword" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ConfirmPassword"></label>
                    <input asp-for="ConfirmPassword" class="form-control" />
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

Eventique/Views/Photographers/CreateNewAlbum.cshtml
@model Album
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "CreateNewAlbum";
    Layout = "~/Views/Shared/_BackViewLayout.cshtml";
}


<div id="colorlib-main">
<section class="ftco-section contact-section">
    <div class="container">
        <div class="row block-9">   
            <div class="col-md-12 order-md-last pr-md-5">
                <h1>Creating new Album</h1>
                <hr />
                <form method="post" enctype="multipart/form-data" asp-controller="Photographers" asp-action="CreateNewAlbum">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Al_Title" class="control-label"></label>
                        <input asp-for="Al_Title" class="form-control" />
                        <span asp-validation-for="Al_Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ImageFilePath" class="control-label"></label>
                        <input type="file" asp-for="ImageFilePath" class="form-control" multiple />
                        <span asp-validation-for="ImageFilePath" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Add" class="btn btn-primary py-3 px-5">
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>
    </div>

Eventique/Views/Photographers/Deals.cshtml
@model Eventique.Models.Photographer
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "Deals";
    Layout = "~/Views/Shared/_BackViewLayout.cshtml";
}

@section Styles{
    <link rel="stylesheet" href="~/Calendar/style.css">
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet" />

}
@if (SignInManager.IsSignedIn(User))
{
    if (User.Identity.Name != Model.Users.Email)
    {
        <div id="colorlib-main">
            <section class="ftco-section contact-section">
                <div class="container">
                    <div class="row block-9" style="text-align:center">
                        <h1>You Tried to Access page not found </h1>
                        <h2>if you entered agian you will be blocked </h2>
                    </div>
                </div>
            </section>
        </div>
    }
    else
    {
        <!----------------------------------------------------------popup Section Hidden------------------------------------------------------>
        @*<div class="modal fade" tabindex="-1" id="ModalStatus" data-keyboard="false" data-backdrop="static" style="z-index:2000">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <form method="post" asp-controller="Photographers" asp-action="Update">
                        <input type="hidden" name="Inv_Id" id="Inv_Id" />
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Post a Request</h4>
                        </div>
                        <div class="modal-body">
                            <p> Are you sure you want to accept that deal?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success">Accept</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>*@
        <!------------------------------------------------------------------End popup Section Hidden---------------------------------------------------------------------->

        <div id="colorlib-main">
            <section class="ftco-section contact-section">
                <div class="container">
                    <div class="row block-9">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Request ID</th>
                                    <th>Avatar</th>
                                    <th>Name</th>
                                    <th>Date</th>
                                    <th>Price</th>
                                    <th>Message</th>
                                    <th>Request Time</th>
                                    <th>Status</th>
                                    <th>Reply</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    foreach (var item in Model.Ph_Requests)
                                    {
                                        <tr>
                                            <td>@item.ID</td>
                                            <td>
                                                <div class="round-img">
                                                    <a href="#"><img class="rounded-circle" width="60" height="60" src="@item.RequestUser.ImagePath" alt=""></a>
                                                </div>
                                            </td>
                                            <td>@item.RequestUser.Name</td>
                                            <td>@item.Date</td>
                                            <td>@Model.Ph_Price</td>
                                            <td>@item.Message</td>
                                            <td>@item.Time</td>
                                            <td>@item.Status</td>
                                            <td>
                                                <form method="post" action="~/Photographers/AcceptDeal/@item.ID" >
                                                    <button type="submit" id="btnaccept" class="btn btn-success edit" onclick="disable()">
                                                        Accept
                                                    </button>
                                                </form>
                                                <form method="post" action="~/Photographers/CancelDeal/@item.ID">
                                                    <button type="submit" id="btncancel" class="btn btn-danger" onclick="Enable()">
                                                        Cancel
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    }
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </section>
        </div>
        <script>
            const button = document.querySelector('#btnaccept')
            const button2 = document.querySelector('#btncancel')
            function disable() {
                button.style.visibility = "hidden";
                button2.style.visibility = "visible";
            }
            function Enable() {
                button.style.visibility = "visible";
                button2.style.visibility = "hidden";
            }
        </script>

    }
}

Eventique/Views/Photographers/EditPho.cshtml
@model Eventique.Models.Photographer
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "EditPho";
    Layout = "~/Views/Shared/_BackViewLayout.cshtml";
}

@section Styles{
    <link rel="stylesheet" href="~/Calendar/style.css">
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet" />

}
@if (SignInManager.IsSignedIn(User))
{
    if (User.Identity.Name != Model.Users.Email)
    {
        <div id="colorlib-main">
            <section class="ftco-section contact-section">
                <div class="container">
                    <div class="row block-9" style="text-align:center">
                        <h1>You Tried to Access page not found </h1>
                        <h2>if you entered agian you will be blocked </h2>
                    </div>
                </div>
             </section>
        </div>
    }
    else
    {
    <div id="colorlib-main">
        <section class="ftco-section contact-section">
            <div class="container">
                <div class="row block-9">
                    <div class="col-md-12 order-md-last pr-md-5">
                        <div class="form-group">
                            <!-- Message -->
                            <a asp-controller="Photographers" asp-action="ChangePassword">
                                <button type="button" class="btn btn-danger">
                                    Chang password
                                </button>
                            </a>
                        </div>
                        <form class="wrap-form-reservation size22 m-l-r-auto" method="post" enctype="multipart/form-data" asp-controller="Photographers" asp-action="EditPho">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Ph_Id" />

                            <div class="form-group">
                                <!-- Name -->
                                <label asp-for="Ph_Name">Name</label>
                                <input asp-for="Ph_Name" class="form-control" placeholder="Name">
                                <span asp-validation-for="Ph_Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <!-- Phone Number -->
                                <label asp-for="Users.PhoneNumber"></label>
                                <input asp-for="Users.PhoneNumber" class="form-control" placeholder="PhoneNumber">
                                <span asp-validation-for="Users.PhoneNumber" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <!-- Price -->
                                <label asp-for="Ph_Price" class="txt9">enter your startup Price</label>
                                <input asp-for="Ph_Price" class="form-control" placeholder="price LE">
                                <span asp-validation-for="Ph_Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <!-- Address -->
                                <label asp-for="Ph_Address" class="txt9">enter your Address</label>
                                <input asp-for="Ph_Address" class="form-control" placeholder="Adress">
                                <span asp-validation-for="Ph_Address" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <!-- camera type -->
                                <label asp-for="Ph_CameraType" class="txt9">Camera Type</label>
                                <input asp-for="Ph_CameraType" class="form-control" placeholder="Adress">
                                <span asp-validation-for="Ph_CameraType" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <!-- ImgPath -->
                                <label asp-for="ImagePath" class="txt9">your Image Path </label>
                                <input asp-for="ImagePath" class="form-control" placeholder="your Image Path ">
                                <span asp-validation-for="ImagePath" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageFilePath" class="txt9"></label>
                                <input type="file" asp-for="ImageFilePath" class="bo-rad-10 sizefull txt10 p-l-20" />
                                <span asp-validation-for="ImageFilePath" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="TestDate"></label>
                                <input type="text" class="form-control date" asp-for="TestDate" placeholder="Pick the multiple dates" id="inputDate">
                            </div>
                            <div class="form-group">
                                <!-- Description -->
                                <label asp-for="Description">Enter your Offer Description</label>
                                <textarea asp-for="Ph_Offers" class="form-control" placeholder="Enter your info more about you"></textarea>
                            </div>
                            <div class="form-group">
                                <!-- Message -->
                                <label asp-for="Ph_Offers">Enter your Offer Description</label>
                                <textarea asp-for="Ph_Offers" class="form-control" placeholder="Enter your Offer Description"></textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Edit" class="btn btn-primary py-3 px-5">
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </section>
    </div>

    }
    }

@section Scripts{
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js'></script>
    <script src="~/Calendar/script.js"></script>
}